### PR TITLE
Reduce wasted space on triploe cistatus page header

### PR DESCRIPTION
**Pull request by ssbarnea**
- makes logo small
- makes menu links horizontal
- allow menu items to wrap on smaller screens
- improves contrast on menu items
- replace hardcoded urls with one relative to website root
- removes repeated "jobs" suffix on each menu item

### CODE REVIEW

**Comment by ssbarnea** [comment]
image

**Comment by ssbarnea** [comment]
@weshayutin @sshnaidm --- got tired of scrolling in the statu spage where 50% of page size was taken by the static header.

**Review by sshnaidm — APPROVED** [review]
Thanks

**Comment by sshnaidm** [comment]
@ssbarnea  You'd better to do it also for branches: gates, promtest, they are responsible for promotion and gates jobs pages. And if you want also for rdoci branch - it's phase1.

**Pull request merged**
