### PR TITLE
Add rdoproject.org dashboards

### LINKED ISSUE #30: Add links to RDO dlrnapi dashboards
Add links in sova to the dashboards at rdoproject.org

- https://dashboards.rdoproject.org/rdo-dev
- https://dashboards.rdoproject.org/master
- https://dashboards.rdoproject.org/pike
- https://dashboards.rdoproject.org/ocata

(coming soon)

- https://dashboards.rdoproject.org/queens

### PR DESCRIPTION
**Pull request by halcyondude**
Add links to the dashboards at rdoproject.org

- https://dashboards.rdoproject.org/rdo-dev
- https://dashboards.rdoproject.org/master
- https://dashboards.rdoproject.org/pike
- https://dashboards.rdoproject.org/ocata

This commit resolves #30

### CODE REVIEW

**Comment by halcyondude** [comment]
@weshayutin @sshnaidm 

Please advise on which other branches this commit should be merged to.

Regarding the TODO, when https://review.rdoproject.org/r/#/c/12616 lands will update for queens.

**Review by weshayutin — CHANGES_REQUESTED** [review]
There is no context re: this links what they are for.  The links are also not aligned to each release following  the titles for each release section.

This should be moved to --> http://38.145.34.234/  --> Under the graphs
Master-promotion - <a href="http://dashboards.rdoproject.org/rdo-dev/master">promotion dashboard</a>,

Queens-promotion - <a href="http://dashboards.rdoproject.org/rdo-dev/queens">promotion dashboard</a>,

etc.. for pike, ocata

**Comment by halcyondude** [comment]
the way sova is constructed this is something of a heavy lift, as "release" isn't modeled in the input, there are just column names, some of which are named {release}-promotion (but without release being abstracted).

The combination of jinja / python / config.py / html template means changes throughout all layers.  I cranked for about a day before falling back to a simple solution.

column names are generated here: 

https://github.com/halcyondude/sova/blob/master/html/jobs_list.html#L10

data for template is created here:

https://github.com/halcyondude/sova/blob/master/tripleoci/page.py#L73

with this:

```
    jobs_by_column = sorted([(i, [os.path.basename(k) for k in j if
                                  os.path.basename(k) in all_job_names])
                             for i, j in config.COLUMNED_TRACKED_JOBS.items()],
                            key=lambda x: len(x[1]), reverse=True)
```

Which is fed by input data from config.py here:

https://github.com/halcyondude/sova/blob/master/tripleoci/config.py#L94

and the "COLUMNED_TRACKED_JOBS" input from config.py is different for each branch (corresponding to each installed instance).

Ways I came up with to do this...

- The HTML template could be updated to match the names used in config.py (e.g. "Master-promotion") but it would have to be hard coded for those, which seems overly fragile, and involves ninja-jinja
- update the underlying data structure passed to the jinja template to include an (optional) dashboard link with the above stuff re-written.  This means changes (in all branches) to config.py as well as changing the page template as well as create_html function
- park it in the header with a few lines of HTML :)

I prefer the middle choice as it's cleaner, but does involve more work.  Thoughts?

**Comment by halcyondude** [comment]
@weshayutin had a cool idea I had not considered, just hack the config to include the links there, so {{column}} already includes the link from config.py input.  Testing that out now...

**Comment by halcyondude** [comment]
PR update incoming that injects the links via config.py.  it was also necessary to add an onclick handler to override the bootstrap nav class's swallowing of the click events

links-new-approach


The titles (e.g. "Pike-promotion") are links to the dashboards...

**Comment by halcyondude** [comment]
Added a link to queens dashboard now that https://dashboards.rdoproject.org/queens is live.

**Review by sshnaidm — APPROVED** [review]
thanks!

**Pull request merged**
